// frontend/src/app/presentation/home/landing-deep/landing-deep.component.ts
import { AfterViewInit, Component, ElementRef, HostListener, ViewChild, ViewChildren, QueryList } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-landing-deep',
  imports: [RouterModule],
  templateUrl: './landing-deep.component.html',
  styleUrl: './landing-deep.component.scss'
})
export class LandingDeepComponent implements AfterViewInit {
  isScrolled = false;
  menuOpen = false;

  @ViewChild('navEl') navEl!: ElementRef<HTMLElement>;
  @ViewChildren('featureCard') featureCards!: QueryList<ElementRef<HTMLElement>>;

  ngAfterViewInit(): void {
    this.setupScrollObserver();
  }

  @HostListener('window:scroll')
  onScroll(): void {
    this.isScrolled = window.scrollY > 40;
  }

  private setupScrollObserver(): void {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
          }
        });
      },
      { threshold: 0.1, rootMargin: '0px 0px -40px 0px' }
    );

    this.featureCards.forEach((card) => {
      observer.observe(card.nativeElement);
    });
  }
}

<div class="landing-wrapper">
  <!-- NAVBAR -->
  <nav class="landing-nav" [class.scrolled]="isScrolled" #navEl>
    <div class="container">
      <div class="d-flex align-items-center justify-content-between">
        <a class="nav-brand" href="#hero">VendeDTo</a>

        <div class="d-none d-lg-flex align-items-center gap-4">
          <a class="nav-auth-link" href="#caracteristicas">Características</a>
          <a class="nav-auth-link" href="#como-funciona">Cómo funciona</a>
          <a class="btn-primary-amber" [routerLink]="['/register']">
            Comenzar
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </a>
        </div>

        <button class="d-lg-none nav-toggler" [class.open]="menuOpen" (click)="menuOpen = !menuOpen" aria-label="Menu">
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>

      <div class="nav-dropdown" [class.show]="menuOpen">
        <a class="nav-dropdown-item" href="#hero" (click)="menuOpen = false">Inicio</a>
        <a class="nav-dropdown-item" href="#caracteristicas" (click)="menuOpen = false">Características</a>
        <a class="nav-dropdown-item" href="#como-funciona" (click)="menuOpen = false">Cómo funciona</a>
        <a class="nav-dropdown-item" [routerLink]="['/login']" (click)="menuOpen = false">Iniciar sesión</a>
        <a class="nav-dropdown-item" [routerLink]="['/register']" (click)="menuOpen = false" style="color: #f5b026; font-weight: 600"
          >Comenzar gratis</a
        >
      </div>
    </div>
  </nav>

  <!-- HERO -->
  <section id="hero" class="hero-section">
    <div class="hero-bg-grid"></div>
    <div class="hero-bg-glow"></div>

    <div class="container position-relative">
      <div class="row align-items-center g-5">
        <!-- Left: Copy -->
        <div class="col-lg-6">
          <p class="hero-eyebrow">Punto de venta offline</p>
          <h1 class="hero-title">
            Vende más.<br />
            Controla <span class="accent">todo.</span>
          </h1>
          <p class="hero-sub">
            Gestiona tu negocio sin depender de Internet. Ventas, inventario, cuadre de caja y reportes — siempre disponibles en tu
            dispositivo.
          </p>
          <div class="hero-actions">
            <a [routerLink]="['/register']" class="btn-primary-amber">
              Prueba gratis
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </a>
            <a href="#caracteristicas" class="btn-ghost">
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <circle cx="8" cy="8" r="6" stroke="currentColor" stroke-width="1.5" />
                <path d="M6.5 5.5l4 2.5-4 2.5v-5z" fill="currentColor" />
              </svg>
              Ver características
            </a>
          </div>
        </div>

        <!-- Right: Stats card -->
        <div class="col-lg-5 offset-lg-1">
          <div class="hero-card">
            <div class="hero-card-stat">
              <span class="hero-card-number">24</span>
              <span class="hero-card-label">hrs sin conexión</span>
            </div>
            <div class="hero-card-stat">
              <span class="hero-card-number">100%</span>
              <span class="hero-card-label">de tus datos</span>
            </div>
            <div class="hero-card-stat">
              <span class="hero-card-number">0</span>
              <span class="hero-card-label">costo mensual</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- FEATURES -->
  <section id="caracteristicas" class="features-section">
    <div class="container">
      <div class="row mb-5 pb-3">
        <div class="col-lg-6">
          <p class="section-eyebrow">Lo que necesitas</p>
          <h2 class="section-title">Todo para gestionar<br />tu negocio</h2>
        </div>
        <div class="col-lg-5 offset-lg-1 d-flex align-items-end">
          <p class="section-subtitle"> Una herramienta completa que crece contigo. Sin suscripciones, sin complicaciones, sin internet. </p>
        </div>
      </div>

      <div class="row g-4">
        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M14 2L4 6v8c0 5.5 4.3 10.7 10 12 5.7-1.3 10-6.5 10-12V6L14 2z"
                  stroke="#f5b026"
                  stroke-width="1.5"
                  stroke-linejoin="round"
                />
                <rect x="9" y="12" width="10" height="8" rx="1.5" stroke="#f5b026" stroke-width="1.5" />
                <path d="M12 12v-2a2 2 0 0 1 4 0v2" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <circle cx="14" cy="16" r="1" fill="#f5b026" />
              </svg>
            </div>
            <h3 class="feature-title">Seguridad total</h3>
            <p class="feature-desc">Tus datos se guardan en el teléfono. Nadie más accede a ellos, nunca.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M14 20c4.4 0 8-2.7 8-6s-3.6-6-8-6-8 2.7-8 6 3.6 6 8 6z" stroke="#f5b026" stroke-width="1.5" />
                <path d="M10 14c1.7-1 3.4-1.5 4-1.5s2.3.5 4 1.5" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <path d="M4 20V8" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <path d="M24 20V8" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="6" y1="6" x2="22" y2="22" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
              </svg>
            </div>
            <h3 class="feature-title">Funciona sin Internet</h3>
            <p class="feature-desc">Todas las funciones disponibles sin conexión. Solo la autenticación requiere red.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M15.5 3L8 15h7l-1.5 10L22 13h-7l1-7L15.5 3z"
                  stroke="#f5b026"
                  stroke-width="1.5"
                  stroke-linejoin="round"
                  stroke-linecap="round"
                />
                <circle cx="15.5" cy="13" r="2" fill="#f5b026" fill-opacity="0.2" stroke="#f5b026" stroke-width="1" />
              </svg>
            </div>
            <h3 class="feature-title">Registro instantáneo</h3>
            <p class="feature-desc">Anota cada venta en segundos. Sin papel, sin cálculos manuales.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect x="3" y="8" width="22" height="15" rx="2" stroke="#f5b026" stroke-width="1.5" />
                <path d="M8 8V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2" stroke="#f5b026" stroke-width="1.5" />
                <line x1="3" y1="14" x2="25" y2="14" stroke="#f5b026" stroke-width="1.5" />
                <rect x="7" y="17" width="4" height="3" rx="0.5" fill="#f5b026" fill-opacity="0.3" stroke="#f5b026" stroke-width="0.75" />
                <rect x="13" y="17" width="4" height="3" rx="0.5" fill="#f5b026" fill-opacity="0.3" stroke="#f5b026" stroke-width="0.75" />
                <path d="M19 17v3M22 18.5h.01" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
              </svg>
            </div>
            <h3 class="feature-title">Cuadre de caja rápido</h3>
            <p class="feature-desc">Cierra tu día en minutos con totales y diferencias calculadas automáticamente.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4 8l10-4 10 4v4l-10 4-10-4V8z" stroke="#f5b026" stroke-width="1.5" stroke-linejoin="round" />
                <path d="M4 12l10 4 10-4M14 16v8" stroke="#f5b026" stroke-width="1.5" stroke-linejoin="round" />
                <path d="M14 20l-10-4M14 20l10-4" stroke="#f5b026" stroke-width="1.5" />
              </svg>
            </div>
            <h3 class="feature-title">Inventario en tiempo real</h3>
            <p class="feature-desc">Consulta cuánto tienes y cuánto vale tu stock al instante.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <line x1="5" y1="22" x2="5" y2="14" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="10" y1="22" x2="10" y2="9" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="15" y1="22" x2="15" y2="5" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="20" y1="22" x2="20" y2="12" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="25" y1="22" x2="25" y2="17" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="3" y1="22" x2="27" y2="22" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <path d="M15 5l4-2M19 3l-4 2" stroke="#f5b026" stroke-width="1" stroke-linecap="round" />
              </svg>
            </div>
            <h3 class="feature-title">Reportes claros</h3>
            <p class="feature-desc">Ganancias del día, productos más vendidos y tendencias — con un clic.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect x="5" y="3" width="18" height="22" rx="2" stroke="#f5b026" stroke-width="1.5" />
                <line x1="9" y1="9" x2="19" y2="9" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="9" y1="13" x2="19" y2="13" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="9" y1="17" x2="15" y2="17" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <circle cx="20" cy="21" r="6" fill="#0a0a0a" stroke="#f5b026" stroke-width="1.5" />
                <path d="M18 21l1.5 1.5L22 19.5" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </div>
            <h3 class="feature-title">Facturación integrada</h3>
            <p class="feature-desc">Emite facturas PDF al registrar cada venta, sin pasos extra.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect x="3" y="3" width="22" height="22" rx="2" stroke="#f5b026" stroke-width="1.5" />
                <path d="M3 9h22" stroke="#f5b026" stroke-width="1.5" />
                <path d="M8 9V20a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9" stroke="#f5b026" stroke-width="1.25" />
                <path d="M14 9v7a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9" stroke="#f5b026" stroke-width="1.25" />
                <path d="M20 9v4a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9" stroke="#f5b026" stroke-width="1.25" />
                <line x1="6" y1="12" x2="11" y2="12" stroke="#f5b026" stroke-width="1" stroke-linecap="round" stroke-dasharray="1.5 1.5" />
              </svg>
            </div>
            <h3 class="feature-title">Panel de decisiones</h3>
            <p class="feature-desc">Visualiza datos clave para planificar mejor y vender más.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M5 12a3 3 0 0 1 3-3h4l3-3h5a3 3 0 0 1 3 3v1a3 3 0 0 1-3 3h-1"
                  stroke="#f5b026"
                  stroke-width="1.5"
                  stroke-linecap="round"
                />
                <path d="M23 12v4a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3v-4" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <path d="M14 10v4a3 3 0 0 0 3 3h1" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" />
                <line x1="5" y1="8" x2="14" y2="8" stroke="#f5b026" stroke-width="1.5" stroke-linecap="round" stroke-dasharray="2 2" />
              </svg>
            </div>
            <h3 class="feature-title">Sincronización flexible</h3>
            <p class="feature-desc">Sube y descarga tus datos cuando lo necesites, sin perder información.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- HOW IT WORKS -->
  <section id="como-funciona" class="features-section" style="border-top: 1px solid rgba(245, 176, 66, 0.06)">
    <div class="container">
      <div class="text-center mb-5 pb-3">
        <p class="section-eyebrow" style="justify-content: center">
          <span style="display: block; width: 24px; height: 1px; background: #f5b026"></span>
          En tres pasos
        </p>
        <h2 class="section-title" style="margin-left: auto; margin-right: auto">Así de simple</h2>
      </div>

      <div class="row g-5">
        <div class="col-md-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap" style="margin-bottom: 1.5rem">
              <span style="font-family: 'Space Grotesk', sans-serif; font-size: 1.6rem; font-weight: 700; color: #f5b026; line-height: 1"
                >01</span
              >
            </div>
            <h3 class="feature-title">Regístrate</h3>
            <p class="feature-desc">Crea tu cuenta en segundos. Solo necesitas un correo y una contraseña.</p>
          </div>
        </div>

        <div class="col-md-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap" style="margin-bottom: 1.5rem">
              <span style="font-family: 'Space Grotesk', sans-serif; font-size: 1.6rem; font-weight: 700; color: #f5b026; line-height: 1"
                >02</span
              >
            </div>
            <h3 class="feature-title">Configura tu punto</h3>
            <p class="feature-desc">Agrega productos al catálogo y registra tu inventario inicial.</p>
          </div>
        </div>

        <div class="col-md-4">
          <div class="feature-card" #featureCard>
            <div class="feature-icon-wrap" style="margin-bottom: 1.5rem">
              <span style="font-family: 'Space Grotesk', sans-serif; font-size: 1.6rem; font-weight: 700; color: #f5b026; line-height: 1"
                >03</span
              >
            </div>
            <h3 class="feature-title">Empieza a vender</h3>
            <p class="feature-desc">Registra cada venta, consulta tu cuadre y reportes. Así de fácil.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- CTA -->
  <section id="registro" class="cta-section">
    <div class="cta-bg-element"></div>
    <div class="container">
      <div class="cta-inner">
        <p class="section-eyebrow" style="justify-content: center; margin-bottom: 1.5rem">
          <span style="display: block; width: 24px; height: 1px; background: #f5b026"></span>
          Empieza hoy
        </p>
        <h2 class="cta-title"> Tu negocio merece<br />las mejores herramientas </h2>
        <p class="cta-sub"> Únete a cientos de emprendedores que ya gestionan sus ventas con control y seguridad. </p>
        <a [routerLink]="['/register']" class="btn-primary-amber" style="font-size: 1rem; padding: 1rem 2.5rem">
          Crear cuenta gratis
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </a>
        <p
          style="
            margin-top: 1.25rem;
            font-family: 'Space Grotesk', sans-serif;
            font-size: 0.75rem;
            color: rgba(245, 240, 235, 0.3);
            letter-spacing: 0.04em;
          "
        >
          Sin tarjeta de crédito · Sin suscripciones mensuales
        </p>
      </div>
    </div>
  </section>

  <!-- FOOTER -->
  <footer class="footer">
    <div class="container">
      <p class="footer-text mb-0"> &copy; 2026 VendeDTo · Desarrollado con ♥ para emprendedores </p>
    </div>
  </footer>
</div>

// frontend-react/apps/web-store-pos/app/home/routes/landing-deep.tsx
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router';
import { Button } from '~/shared/components/ui/button';
import { CloseIcon } from '~/shared/components/ui/icons';
import './landing-deep.css';

// Mirrors Button's primary variant (ui/button.tsx VARIANT_CLASSES.primary) for
// anchor/Link CTAs: a real <button> can't be nested inside <a>/<Link>, so route
// and in-page-anchor CTAs apply the same token utilities inline instead.
const ctaPrimary =
  'inline-flex items-center justify-center gap-2 rounded-md px-4 py-2 shadow-card ' +
  'bg-primary text-white text-sm font-medium transition-colors hover:bg-primary-hover';

// Mirrors Button's outline variant, retinted for use over the hero's brand
// gradient (border-primary/text-primary would be invisible against a
// primary-colored background — the hero already uses white/N opacity steps
// for its glass stats card, so this follows the same pattern).
const ctaOutlineOnGradient =
  'inline-flex items-center justify-center gap-2 rounded-md px-4 py-2 border ' +
  'border-white/30 text-white text-sm font-medium transition-colors hover:bg-white/10';

const FEATURES: Array<{ title: string; desc: string; icon: React.ReactNode }> = [
  {
    title: 'Seguridad total',
    desc: 'Tus datos se guardan en el teléfono. Nadie más accede a ellos, nunca.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M14 2L4 6v8c0 5.5 4.3 10.7 10 12 5.7-1.3 10-6.5 10-12V6L14 2z"
          stroke="#f5b026"
          strokeWidth="1.5"
          strokeLinejoin="round"
        />
        <rect x="9" y="12" width="10" height="8" rx="1.5" stroke="#f5b026" strokeWidth="1.5" />
        <path d="M12 12v-2a2 2 0 0 1 4 0v2" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <circle cx="14" cy="16" r="1" fill="#f5b026" />
      </svg>
    ),
  },
  {
    title: 'Funciona sin Internet',
    desc: 'Todas las funciones disponibles sin conexión. Solo la autenticación requiere Internet.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M14 20c4.4 0 8-2.7 8-6s-3.6-6-8-6-8 2.7-8 6 3.6 6 8 6z" stroke="#f5b026" strokeWidth="1.5" />
        <path d="M10 14c1.7-1 3.4-1.5 4-1.5s2.3.5 4 1.5" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <path d="M4 20V8" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <path d="M24 20V8" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="6" y1="6" x2="22" y2="22" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: 'Registro instantáneo',
    desc: 'Anota cada venta en segundos. Sin papel, sin cálculos manuales.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M15.5 3L8 15h7l-1.5 10L22 13h-7l1-7L15.5 3z"
          stroke="#f5b026"
          strokeWidth="1.5"
          strokeLinejoin="round"
          strokeLinecap="round"
        />
        <circle cx="15.5" cy="13" r="2" fill="#f5b026" fillOpacity="0.2" stroke="#f5b026" strokeWidth="1" />
      </svg>
    ),
  },
  {
    title: 'Cuadre de caja rápido',
    desc: 'Cierra tu día en minutos con totales y diferencias calculadas automáticamente.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="3" y="8" width="22" height="15" rx="2" stroke="#f5b026" strokeWidth="1.5" />
        <path d="M8 8V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2" stroke="#f5b026" strokeWidth="1.5" />
        <line x1="3" y1="14" x2="25" y2="14" stroke="#f5b026" strokeWidth="1.5" />
        <rect x="7" y="17" width="4" height="3" rx="0.5" fill="#f5b026" fillOpacity="0.3" stroke="#f5b026" strokeWidth="0.75" />
        <rect x="13" y="17" width="4" height="3" rx="0.5" fill="#f5b026" fillOpacity="0.3" stroke="#f5b026" strokeWidth="0.75" />
        <path d="M19 17v3M22 18.5h.01" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: 'Inventario en tiempo real',
    desc: 'Consulta cuánto tienes y cuánto vale tu stock al instante.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M4 8l10-4 10 4v4l-10 4-10-4V8z" stroke="#f5b026" strokeWidth="1.5" strokeLinejoin="round" />
        <path d="M4 12l10 4 10-4M14 16v8" stroke="#f5b026" strokeWidth="1.5" strokeLinejoin="round" />
        <path d="M14 20l-10-4M14 20l10-4" stroke="#f5b026" strokeWidth="1.5" />
      </svg>
    ),
  },
  {
    title: 'Reportes claros',
    desc: 'Ganancias del día, productos más vendidos y tendencias — con un clic.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <line x1="5" y1="22" x2="5" y2="14" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="10" y1="22" x2="10" y2="9" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="15" y1="22" x2="15" y2="5" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="20" y1="22" x2="20" y2="12" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="25" y1="22" x2="25" y2="17" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="3" y1="22" x2="27" y2="22" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <path d="M15 5l4-2M19 3l-4 2" stroke="#f5b026" strokeWidth="1" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: 'Facturación integrada',
    desc: 'Emite facturas PDF al registrar cada venta, sin pasos extra.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="5" y="3" width="18" height="22" rx="2" stroke="#f5b026" strokeWidth="1.5" />
        <line x1="9" y1="9" x2="19" y2="9" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="9" y1="13" x2="19" y2="13" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="9" y1="17" x2="15" y2="17" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <circle cx="20" cy="21" r="6" fill="#0a0a0a" stroke="#f5b026" strokeWidth="1.5" />
        <path d="M18 21l1.5 1.5L22 19.5" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    title: 'Panel de decisiones',
    desc: 'Visualiza datos clave para planificar mejor y vender más.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="3" y="3" width="22" height="22" rx="2" stroke="#f5b026" strokeWidth="1.5" />
        <path d="M3 9h22" stroke="#f5b026" strokeWidth="1.5" />
        <path d="M8 9V20a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9" stroke="#f5b026" strokeWidth="1.25" />
        <path d="M14 9v7a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9" stroke="#f5b026" strokeWidth="1.25" />
        <path d="M20 9v4a2 2 0 0 0 2 2h0a2 2 0 0 0 2-2V9" stroke="#f5b026" strokeWidth="1.25" />
        <line x1="6" y1="12" x2="11" y2="12" stroke="#f5b026" strokeWidth="1" strokeLinecap="round" strokeDasharray="1.5 1.5" />
      </svg>
    ),
  },
  {
    title: 'Sincronización flexible',
    desc: 'Sube y descarga tus datos cuando lo necesites, sin perder información.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M5 12a3 3 0 0 1 3-3h4l3-3h5a3 3 0 0 1 3 3v1a3 3 0 0 1-3 3h-1"
          stroke="#f5b026"
          strokeWidth="1.5"
          strokeLinecap="round"
        />
        <path d="M23 12v4a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3v-4" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <path d="M14 10v4a3 3 0 0 0 3 3h1" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" />
        <line x1="5" y1="8" x2="14" y2="8" stroke="#f5b026" strokeWidth="1.5" strokeLinecap="round" strokeDasharray="2 2" />
      </svg>
    ),
  },
];

const STEPS = [
  { number: '01', title: 'Regístrate', desc: 'Crea tu cuenta en segundos. Solo necesitas un teléfono y una contraseña.' },
  { number: '02', title: 'Configura tu punto', desc: 'Agrega productos al catálogo y registra tu inventario inicial.' },
  { number: '03', title: 'Empieza a vender', desc: 'Registra cada venta, consulta tu cuadre y reportes. Así de fácil.' },
];

export default function LandingDeep() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [canInstall, setCanInstall] = useState(false);
  const featureCardRefs = useRef<Array<HTMLDivElement | null>>([]);

  const showLoginButton = !canInstall;

  function closeMenu() {
    setTimeout(() => {
      setMenuOpen(false);
    }, 10);
  }

  // Scroll state for the fixed navbar background
  useEffect(() => {
    function onScroll() {
      setIsScrolled(window.scrollY > 40);
    }
    window.addEventListener('scroll', onScroll);
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  // PWA installability check
  useEffect(() => {
    function checkPWAInstallability() {
      const isStandalone =
        window.matchMedia('(display-mode: standalone)').matches ||
        (window.navigator as Navigator & { standalone?: boolean }).standalone === true;
      const swSupported = 'serviceWorker' in navigator;

      if (swSupported && !isStandalone) {
        setCanInstall(true);
      } else {
        setCanInstall(false);
      }
    }

    checkPWAInstallability();

    function onBeforeInstallPrompt() {
      setCanInstall(true);
    }
    function onAppInstalled() {
      setCanInstall(false);
    }

    window.addEventListener('beforeinstallprompt', onBeforeInstallPrompt);
    window.addEventListener('appinstalled', onAppInstalled);
    return () => {
      window.removeEventListener('beforeinstallprompt', onBeforeInstallPrompt);
      window.removeEventListener('appinstalled', onAppInstalled);
    };
  }, []);

  // Reveal feature cards on scroll into view
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
          }
        });
      },
      { threshold: 0.1, rootMargin: '0px 0px -40px 0px' },
    );

    featureCardRefs.current.forEach((card) => {
      if (card) observer.observe(card);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div className="landing-wrapper">
      {/* NAVBAR */}
      <nav
        className={`fixed inset-x-0 top-0 z-50 py-5 transition-colors${
          isScrolled ? ' bg-surface/85 backdrop-blur border-b border-border' : ''
        }`}
      >
        <div className="mx-auto w-full max-w-6xl px-4">
          <div className="flex items-center justify-between">
            <a className="text-2xl font-bold text-accent" href="#hero">
              VendeDTo
            </a>

            <div className="hidden items-center gap-6 lg:flex">
              <a className="text-sm font-medium uppercase tracking-wide text-text-muted hover:text-accent" href="#caracteristicas">
                Características
              </a>
              <a className="text-sm font-medium uppercase tracking-wide text-text-muted hover:text-accent" href="#como-funciona">
                Cómo funciona
              </a>
              {showLoginButton && (
                <Link className="text-sm font-medium uppercase tracking-wide text-text-muted hover:text-accent" to="/login">
                  Entrar
                </Link>
              )}
              <a className={ctaPrimary} href="#registro">
                Comenzar
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                  <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </a>
            </div>

            <div className="relative lg:hidden">
              <Button variant="outline" className="px-2 py-2" onClick={() => setMenuOpen((v) => !v)} aria-label="Menu">
                {menuOpen ? (
                  <CloseIcon className="h-5 w-5" />
                ) : (
                  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                    <path d="M3 5h14M3 10h14M3 15h14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                  </svg>
                )}
              </Button>

              {menuOpen && (
                <div className="absolute right-0 top-full min-w-[200px] rounded-md border border-border border-t-2 border-t-accent bg-surface py-4 shadow-card">
                  <a className="block px-6 py-2 text-sm text-text hover:bg-accent/5 hover:text-accent" href="#hero" onClick={closeMenu}>
                    Inicio
                  </a>
                  <a
                    className="block px-6 py-2 text-sm text-text hover:bg-accent/5 hover:text-accent"
                    href="#caracteristicas"
                    onClick={closeMenu}
                  >
                    Características
                  </a>
                  <a
                    className="block px-6 py-2 text-sm text-text hover:bg-accent/5 hover:text-accent"
                    href="#como-funciona"
                    onClick={closeMenu}
                  >
                    Cómo funciona
                  </a>
                  <Link
                    className="block px-6 py-2 text-sm text-text hover:bg-accent/5 hover:text-accent"
                    to="/login"
                    onClick={closeMenu}
                  >
                    Iniciar sesión
                  </Link>
                  <a
                    className="block px-6 py-2 text-sm font-semibold text-accent hover:bg-accent/5"
                    href="#registro"
                    onClick={closeMenu}
                  >
                    Comenzar
                  </a>
                </div>
              )}
            </div>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section id="hero" className="hero-section">
        <div className="hero-bg-grid"></div>
        <div className="hero-bg-glow"></div>

        <div className="container position-relative">
          <div className="row align-items-center g-5">
            {/* Left: Copy */}
            <div className="col-lg-6">
              <p className="hero-eyebrow">Punto de venta offline</p>
              <h1 className="hero-title">
                Vende más.
                <br />
                Controla <span className="accent">todo.</span>
              </h1>
              <p className="hero-sub">
                Gestiona tu negocio sin depender de Internet. Ventas, inventario, cuadre de caja y reportes — siempre disponibles en tu
                dispositivo.
              </p>
              <div className="hero-actions">
                <a href="#registro" className="btn-primary-amber">
                  Comenzar
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path
                      d="M3 8h10M9 4l4 4-4 4"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </a>
                <a href="#caracteristicas" className="btn-ghost">
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <circle cx="8" cy="8" r="6" stroke="currentColor" strokeWidth="1.5" />
                    <path d="M6.5 5.5l4 2.5-4 2.5v-5z" fill="currentColor" />
                  </svg>
                  Ver características
                </a>
              </div>
            </div>

            {/* Right: Stats card */}
            <div className="col-lg-5 offset-lg-1">
              <div className="hero-card">
                <div className="hero-card-stat">
                  <span className="hero-card-number">24</span>
                  <span className="hero-card-label">hrs, sin conexión</span>
                </div>
                <div className="hero-card-stat">
                  <span className="hero-card-number">100%</span>
                  <span className="hero-card-label">seguridad de tus datos</span>
                </div>
                <div className="hero-card-stat">
                  <span className="hero-card-number">0</span>
                  <span className="hero-card-label">descontrol</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section id="caracteristicas" className="features-section">
        <div className="container">
          <div className="row mb-5 pb-3">
            <div className="col-lg-6">
              <p className="section-eyebrow">Lo que necesitas</p>
              <h2 className="section-title">
                Todo para gestionar
                <br />
                tu negocio
              </h2>
            </div>
            <div className="col-lg-5 offset-lg-1 d-flex align-items-end">
              <p className="section-subtitle">
                Una herramienta completa que crece contigo. Sin suscripciones, sin complicaciones, sin internet.
              </p>
            </div>
          </div>

          <div className="row g-4">
            {FEATURES.map((feature, index) => (
              <div className="col-md-6 col-lg-4" key={feature.title}>
                <div
                  className="feature-card"
                  ref={(el) => {
                    featureCardRefs.current[index] = el;
                  }}
                >
                  <div className="feature-icon-wrap">{feature.icon}</div>
                  <h3 className="feature-title">{feature.title}</h3>
                  <p className="feature-desc">{feature.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="como-funciona" className="features-section" style={{ borderTop: '1px solid rgba(245, 176, 66, 0.06)' }}>
        <div className="container">
          <div className="text-center mb-5 pb-3">
            <p className="section-eyebrow" style={{ justifyContent: 'center' }}>
              <span style={{ display: 'block', width: 24, height: 1, background: '#f5b026' }}></span>
              En tres pasos
            </p>
            <h2 className="section-title" style={{ marginLeft: 'auto', marginRight: 'auto' }}>
              Así de simple
            </h2>
          </div>

          <div className="row g-5">
            {STEPS.map((step) => (
              <div className="col-md-4" key={step.number}>
                <div className="feature-card">
                  <div className="feature-icon-wrap" style={{ marginBottom: '1.5rem' }}>
                    <span
                      style={{
                        fontFamily: 'var(--font-body)',
                        fontSize: '1.6rem',
                        fontWeight: 700,
                        color: '#f5b026',
                        lineHeight: 1,
                      }}
                    >
                      {step.number}
                    </span>
                  </div>
                  <h3 className="feature-title">{step.title}</h3>
                  <p className="feature-desc">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section id="registro" className="cta-section">
        <div className="cta-bg-element"></div>
        <div className="container">
          <div className="cta-inner">
            <p className="section-eyebrow" style={{ justifyContent: 'center', marginBottom: '1.5rem' }}>
              <span style={{ display: 'block', width: 24, height: 1, background: '#f5b026' }}></span>
              Empieza hoy
            </p>
            <h2 className="cta-title">
              Tu negocio merece
              <br />
              las mejores herramientas
            </h2>
            <p className="cta-sub">Únete a cientos de emprendedores que ya gestionan sus ventas con control y seguridad.</p>
            <Link to="/register" className="btn-primary-amber" style={{ fontSize: '1rem', padding: '1rem 2.5rem' }}>
              Crear cuenta gratis
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </Link>
            <p
              style={{
                marginTop: '1.25rem',
                fontFamily: 'var(--font-body)',
                fontSize: '1rem',
                color: 'rgba(245, 240, 235, 0.3)',
                letterSpacing: '0.04em',
              }}
            >
              2 meses de prueba gratis · Pago mensual post-uso
            </p>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="footer">
        <div className="container">
          <p className="footer-text mb-0">&copy; 2026 VendeDTo · Desarrollado para emprendedores con éxito</p>
        </div>
      </footer>
    </div>
  );
}
