// frontend/src/app/presentation/sale/today-stats/today-stats.component.ts
import { Component, OnInit } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { BehaviorSubject } from 'rxjs';
import { ProductCategoryRepository } from 'src/app/application/categories/product-category.repository';
import { CategoryCartItemsView } from 'src/app/application/orders/category-cart-items.view';
import { OrderOfflineService } from 'src/app/application/orders/order-offline.service';
import { SharedModule } from '../../shared/shared.module';
import { CategoryStatsComponent } from '../category-stats/category-stats.component';
import { Expense } from 'src/app/domain/entities/expenses/expense.model';
import { AuthService } from 'src/app/_services/services.index';
import { UserModel } from 'src/app/_services/auth/_models/auth-user.model';
import { AuthorizationService } from 'src/app/_services/authorization/authorization.service';
import { ExpenseOfflineService } from 'src/app/application/expenses/expense-offline.service';
import { ExpenseListComponent } from '../../expenses/expense-list/expense-list.component';
import { SaleCreditListComponent } from '../sale-credit-list/sale-credit-list.component';
import { SaleCredit } from 'src/app/domain/entities/sale-credits/sale-credit.model';
import { SaleCreditOfflineService } from 'src/app/application/credits/sale-credit-offline.service';
import { PaymentType } from 'src/app/domain/commons/payment-type';

@Component({
    selector: 'app-today-stats',
    imports: [SharedModule, TranslateModule, CategoryStatsComponent, ExpenseListComponent, SaleCreditListComponent],
    templateUrl: './today-stats.component.html',
    styleUrl: './today-stats.component.scss'
})
export class TodayStatsComponent implements OnInit {
  categories$: BehaviorSubject<CategoryCartItemsView[]> = new BehaviorSubject<CategoryCartItemsView[]>([]);
  expenses$: BehaviorSubject<Expense[]> = new BehaviorSubject<Expense[]>([]);
  saleCredits$: BehaviorSubject<SaleCredit[]> = new BehaviorSubject<SaleCredit[]>([]);
  paidSaleCredits$: BehaviorSubject<SaleCredit[]> = new BehaviorSubject<SaleCredit[]>([]);

  currentUser: UserModel;
  hasExpensesModuleAvailable: boolean;
  hasCreditsModuleAvailable: boolean;

  salesCashTotal: number = 0;
  paidCreditsCashTotal: number = 0;
  expensesCashTotal: number = 0;

  constructor(private orderService: OrderOfflineService,
    private expenseService: ExpenseOfflineService,
    private authService: AuthService,
    private authorizationService: AuthorizationService,
    private saleCreditService: SaleCreditOfflineService) {
    this.currentUser = this.authService.currentUserValue;
    this.hasExpensesModuleAvailable = this.authorizationService.hasExpensesModuleAvailable();
    this.hasCreditsModuleAvailable = this.authorizationService.hasCreditsModuleAvailable();
  }

  ngOnInit(): void {
    this.loadCategoryCartItemsView();
    this.setNotCreditSales();
    this.loadExpenses();
    this.loadSaleCredits();
    this.loadPaidSaleCredits();
  }

  loadCategoryCartItemsView() {
    this.orderService.getCategoryCartItemsViewObservable(new Date()).subscribe(response => {
      if (response.succeeded) {
        this.categories$.next(response.data);
      }
    });
    // const categories = this.orderService.getCategoryCartItemsView(new Date()).data;
    // this.categories$.next(categories);
  }

  setNotCreditSales() {
    this.orderService.getActiveTodayOrdersObservable().subscribe(response => {
      if (response && response.succeeded)
        this.salesCashTotal = response.data
            .filter(order => order.paymentType === PaymentType.Efectivo && !order.isCredit)
            .reduce((acc, order) => acc + order.total, 0);
    });
  }

  loadExpenses() {
    if (this.hasExpensesModuleAvailable) {
      this.expenseService.getExpensesInDayObservable(new Date()).subscribe(response => {
        if (response.succeeded) {
          this.expenses$.next(response.data);
          this.expensesCashTotal = this.expenses$.value
            .filter(expense => expense.paymentType === PaymentType.Efectivo)
            .reduce((acc, expense) => acc + expense.total, 0);
        }
      });
    }
  }

  loadSaleCredits() {
    if (this.hasCreditsModuleAvailable) {
      this.saleCreditService.getUnPaidSaleCreditsInDayObservable(new Date()).subscribe(response => {
        if (response.succeeded) {
          this.saleCredits$.next(response.data);
        }
      });
    }
  }

  loadPaidSaleCredits() {
    if (this.hasCreditsModuleAvailable) {
      this.saleCreditService.getPaidSaleCreditsInDayObservable(new Date()).subscribe(response => {
        if (response.succeeded) {
          this.paidSaleCredits$.next(response.data);
          this.paidCreditsCashTotal = this.paidSaleCredits$.value
            .filter(credit => PaymentType.Efectivo === credit.paidType)
            .reduce((acc, credit) => acc + credit.total, 0);
        }
      });
    }
  }

  getOrdersTotal(): number {
    let totalSum: number = 0;
    this.categories$.value.forEach(
      (category) => (totalSum += category.total)
    );
    return totalSum;
  }

  getOrdersItemsCount(): number {
    let itemsCount: number = 0;
    this.categories$.value.forEach(
      (category) => (itemsCount += category.itemsCount)
    );
    return itemsCount;
  }

  getExpensesTotal(): number {
    let totalSum: number = 0;
    this.expenses$.value.forEach(
      (expense) => (totalSum += expense.total)
    );
    return totalSum;
  }

  getExpensesCount(): number {
    return this.expenses$.value.length;
  }

  getTotal(): number {
    return this.getOrdersTotal() + this.getPaidSaleCreditsTotal() - this.getCreditsTotal() - this.getExpensesTotal();
  }

  getPaidSaleCreditsTotal(): number {
    return this.paidSaleCredits$.value.reduce((acc, credit) => acc + credit.total, 0);
  }

  getCashTotal(): number {
    return this.salesCashTotal + this.paidCreditsCashTotal - this.expensesCashTotal;
  }

  getCreditsCount(): number {
    return this.saleCredits$.value.length;
  }

  getCreditsTotal(): number {
    return this.saleCredits$.value.reduce((acc, credit) => acc + credit.total, 0);
  }

  getTotalClassName(): string {
    const total: number = this.getTotal();
    return this.getValueClassName(total);
  }

  getValueClassName(value: number): string {
    return value > 0 ? "text-success" : value < 0 ? "text-danger" : "";
  }
}

<div class="card card-custom">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label" [translate]="'TODAY_STATS.HEADER'"></h3>
        </div>
        <div class="card-toolbar">
            <h3 class="font-weight-bold font-size-lg {{getTotalClassName()}}">
                {{getTotal() | currency:'USD':'symbol':'1.2-2'}}
            </h3>
        </div>
    </div>
    <div class="card-body p-2">
        <mat-accordion multi>
            <mat-expansion-panel [expanded]="false">
                <!-- BEGIN CASH  -->
                <mat-expansion-panel-header class="p-2" class="mat-panel-header">
                    <mat-panel-title>
                        <span class="w-100">Resumen Efectivo</span>
                        <div class="w-100 text-end">
                            <span class="{{getValueClassName(getCashTotal())}}">{{getCashTotal() |
                                currency:'USD':'symbol':'1.2-2'}}</span>
                        </div>
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <div class="table-responsive">
                    <table class="table table-borderless table-vertical-center">
                        <tbody>
                            <tr class="border-1">
                                <td class="p-1">
                                    <span class="mb-1 font-weight-bold font-size-lg text-black">
                                        Ventas
                                    </span>
                                </td>
                                <td class="p-1 text-end">
                                    <span class="mb-1 font-weight-bold font-size-lg text-success">
                                        {{salesCashTotal | currency:'USD':'symbol':'1.2-2'}}
                                    </span>
                                </td>
                            </tr>
                            <tr *ngIf="hasCreditsModuleAvailable" class="border-1">
                                <td class="p-1">
                                    <span class="mb-1 font-weight-bold font-size-lg text-black">
                                        Créditos Pagados
                                    </span>
                                </td>
                                <td class="p-1 text-end">
                                    <span class="mb-1 font-weight-bold font-size-lg text-success">
                                        {{paidCreditsCashTotal | currency:'USD':'symbol':'1.2-2'}}
                                    </span>
                                </td>
                            </tr>
                            <tr *ngIf="hasExpensesModuleAvailable" class="border-1">
                                <td class="p-1">
                                    <span class="mb-1 font-weight-bold font-size-lg text-black">
                                        Gastos
                                    </span>
                                </td>
                                <td class="p-1 text-end">
                                    <span class="mb-1 font-weight-bold font-size-lg text-danger">
                                        {{expensesCashTotal | currency:'USD':'symbol':'1.2-2'}}
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- END CASH  -->
            </mat-expansion-panel>

            <mat-expansion-panel *ngIf="hasExpensesModuleAvailable" [expanded]="false">
                <!-- BEGIN EXPENSES  -->
                <mat-expansion-panel-header class="p-2" class="mat-panel-header">
                    <mat-panel-title>
                        <span class="w-100">Gastos ({{getExpensesCount()}})</span>
                        <div class="w-100 text-end">
                            <span class="text-danger">
                                {{getExpensesTotal() | currency:'USD':'symbol':'1.2-2'}}
                            </span>
                        </div>
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <app-expense-list [expenses$]="expenses$.asObservable()"></app-expense-list>
                <!-- END EXPENSES  -->
            </mat-expansion-panel>

            <mat-expansion-panel *ngIf="hasCreditsModuleAvailable" [expanded]="false">
                <!-- BEGIN CREDITS  -->
                <mat-expansion-panel-header class="p-2" class="mat-panel-header">
                    <mat-panel-title>
                        <span class="w-100">Créditos Por Cobrar ({{getCreditsCount()}})</span>
                        <div class="w-100 text-end">
                            <span class="text-danger">
                                {{getCreditsTotal() | currency:'USD':'symbol':'1.2-2'}}
                            </span>
                        </div>
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <app-sale-credit-list [saleCredits$]="saleCredits$.asObservable()">

                </app-sale-credit-list>
                <!-- END CREDITS  -->
            </mat-expansion-panel>

            <mat-expansion-panel *ngIf="hasCreditsModuleAvailable" [expanded]="false">
                <!-- BEGIN PAID CREDITS  -->
                <mat-expansion-panel-header class="p-2" class="mat-panel-header">
                    <mat-panel-title>
                        <span class="w-100">Créditos Pagados ({{getPaidSaleCreditsTotal()}})</span>
                        <div class="w-100 text-end">
                            <span class="text-success">
                                {{getPaidSaleCreditsTotal() | currency:'USD':'symbol':'1.2-2'}}
                            </span>
                        </div>
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <app-sale-credit-list [saleCredits$]="paidSaleCredits$.asObservable()">

                </app-sale-credit-list>
                <!-- END PAID CREDITS  -->
            </mat-expansion-panel>

            <mat-expansion-panel [expanded]="false">
                <!-- BEGIN SALES  -->
                <mat-expansion-panel-header class="p-2" class="mat-panel-header">
                    <mat-panel-title>
                        <span class="w-100">Ventas ({{getOrdersItemsCount()}} productos)</span>
                        <div class="w-100 text-end">
                            <span class="text-success">
                                {{getOrdersTotal() | currency:'USD':'symbol':'1.2-2'}}
                            </span>
                        </div>
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <app-category-stats *ngFor="let category of categories$ | async" [category]=category></app-category-stats>
                <!-- END SALES  -->
            </mat-expansion-panel>
        </mat-accordion>
    </div>
</div>

// frontend-react/apps/web-store-pos/app/sales/routes/today-stats.tsx
import { useEffect, useState } from 'react';
import { useIntl } from 'react-intl';
import { EFeatures, ExpenseType, PaymentType } from '@store-mgmt/domain';
import type { Expense, Order, SaleCredit } from '@store-mgmt/domain';
import { featureLoader } from '~/auth/routes/loaders';
import { useAuthStore } from '~/shared/lib/stores/auth-store';
import { hasCreditsModuleAvailable, hasExpensesModuleAvailable } from '~/shared/lib/auth/authorization-service';
import { Card } from '~/shared/components/ui/card';
import { OrderOfflineService } from '../lib/services/order-offline-service';
import { ExpenseOfflineService } from '~/expenses/lib/services/expense-offline-service';
import { SaleCreditOfflineService } from '../lib/services/sale-credit-offline-service';
import { CategoryStats } from '../components/category-stats';
import type { CategoryCartItemsView } from '../lib/category-cart-items-view';

export const clientLoader = featureLoader([EFeatures.Sale]);

// Angular's expense-list.component.html column 1 (getExpenseTypeText) — 1:1 mapping,
// duplicated here (not exported by app/expenses/components/expense-list.tsx) to avoid
// coupling the Sales module to the Expenses module's presentational component.
const EXPENSE_TYPE_KEYS: Record<ExpenseType, string> = {
  [ExpenseType.Salario]: 'EXPENSES.TYPE.SALARIO',
  [ExpenseType.Transporte]: 'EXPENSES.TYPE.TRANSPORTE',
  [ExpenseType.Alquiler]: 'EXPENSES.TYPE.ALQUILER',
  [ExpenseType.Corriente]: 'EXPENSES.TYPE.CORRIENTE',
  [ExpenseType.Agua]: 'EXPENSES.TYPE.AGUA',
  [ExpenseType.Comida]: 'EXPENSES.TYPE.COMIDA',
  [ExpenseType.Operaciones]: 'EXPENSES.TYPE.OPERACIONES',
  [ExpenseType.Viaje]: 'EXPENSES.TYPE.VIAJE',
  [ExpenseType.Divisa]: 'EXPENSES.TYPE.DIVISA',
  [ExpenseType.Impuesto]: 'EXPENSES.TYPE.IMPUESTO',
  [ExpenseType.Otro]: 'EXPENSES.TYPE.OTRO',
};

const PAYMENT_TYPE_KEYS: Record<PaymentType, string> = {
  [PaymentType.Efectivo]: 'CART.EFECTIVO',
  [PaymentType.Tarjeta]: 'CART.TARJETA',
  [PaymentType.Zelle]: 'CART.ZELLE',
};

function valueClassName(value: number): string {
  return value > 0 ? 'text-success' : value < 0 ? 'text-danger' : 'text-text';
}

/**
 * `<details>`/`<summary>` panel matching Angular Material's `mat-expansion-panel`
 * (collapsed by default, `[expanded]="false"` in every panel on this view).
 */
function ExpansionPanel({
  title,
  amount,
  amountClassName,
  children,
}: {
  title: string;
  amount: string;
  amountClassName: string;
  children: React.ReactNode;
}) {
  return (
    <details className="border-b border-border last:border-0">
      <summary className="flex cursor-pointer list-none items-center justify-between p-2 text-sm font-medium text-text hover:bg-primary-light/40">
        <span>{title}</span>
        <span className={amountClassName}>{amount}</span>
      </summary>
      <div className="p-2">{children}</div>
    </details>
  );
}

/**
 * 1:1 port of Angular's `today-stats.component.html` ("Cuadre del día"): a card with the
 * running total in the toolbar, and an accordion of collapsed-by-default panels — Resumen
 * Efectivo (always), Gastos (if hasExpensesModuleAvailable), Créditos Por Cobrar (if
 * hasCreditsModuleAvailable), Créditos Pagados (if hasCreditsModuleAvailable), and Ventas
 * (always, rendering one CategoryStats row per category).
 */
export function TodayStatsPage() {
  const intl = useIntl();
  const user = useAuthStore((s) => s.user);
  const storeId = user?.selectedStoreId ?? '';

  const hasExpensesModule = user ? hasExpensesModuleAvailable(user) : false;
  const hasCreditsModule = user ? hasCreditsModuleAvailable(user) : false;

  const [categories, setCategories] = useState<CategoryCartItemsView[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [saleCredits, setSaleCredits] = useState<SaleCredit[]>([]);
  const [paidSaleCredits, setPaidSaleCredits] = useState<SaleCredit[]>([]);
  const [salesCashTotal, setSalesCashTotal] = useState(0);

  useEffect(() => {
    const orderService = new OrderOfflineService(storeId);
    setCategories(orderService.getCategoryCartItemsView(new Date()).data);

    const activeOrders: Order[] = orderService.getActiveOrdersInDay(new Date());
    setSalesCashTotal(
      activeOrders
        .filter((o) => o.paymentType === PaymentType.Efectivo && !o.isCredit)
        .reduce((acc, o) => acc + o.total, 0),
    );

    if (hasExpensesModule) {
      // Angular parity (today-stats.component.ts:79): loads today's expenses via
      // getExpensesInDayObservable(new Date()) and unwraps the BaseResponseModel `.data`.
      const expenseService = new ExpenseOfflineService(storeId);
      void expenseService
        .getExpensesInDayObservable(new Date())
        .then((response) => setExpenses(response.data));
    }

    if (hasCreditsModule) {
      // Angular parity (today-stats.component.ts:92,102): loads via
      // getUnPaidSaleCreditsInDayObservable/getPaidSaleCreditsInDayObservable and unwraps
      // the BaseResponseModel `.data` (flagged mismatch #3).
      const creditService = new SaleCreditOfflineService(storeId);
      void creditService
        .getUnPaidSaleCreditsInDayObservable(new Date())
        .then((response) => setSaleCredits(response.data));
      void creditService
        .getPaidSaleCreditsInDayObservable(new Date())
        .then((response) => setPaidSaleCredits(response.data));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [storeId, hasExpensesModule, hasCreditsModule]);

  const expensesCashTotal = expenses
    .filter((e) => e.paymentType === PaymentType.Efectivo)
    .reduce((acc, e) => acc + e.total, 0);
  const paidCreditsCashTotal = paidSaleCredits
    .filter((c) => c.paidType === PaymentType.Efectivo)
    .reduce((acc, c) => acc + c.total, 0);

  const ordersTotal = categories.reduce((acc, c) => acc + c.total, 0);
  const ordersItemsCount = categories.reduce((acc, c) => acc + c.itemsCount, 0);
  const expensesTotal = expenses.reduce((acc, e) => acc + e.total, 0);
  const expensesCount = expenses.length;
  const paidSaleCreditsTotal = paidSaleCredits.reduce((acc, c) => acc + c.total, 0);
  const cashTotal = salesCashTotal + paidCreditsCashTotal - expensesCashTotal;
  const creditsCount = saleCredits.length;
  const creditsTotal = saleCredits.reduce((acc, c) => acc + c.total, 0);
  const total = ordersTotal + paidSaleCreditsTotal - creditsTotal - expensesTotal;

  return (
    <Card
      title={
        <div className="flex items-center justify-between">
          {/* TODAY_STATS.HEADER */}
          <span>{intl.formatMessage({ id: 'TODAY_STATS.HEADER' })}</span>
          <span className={`text-lg font-bold ${valueClassName(total)}`}>
            ${total.toFixed(2)}
          </span>
        </div>
      }
    >
      <div className="divide-y divide-border">
        {/* BEGIN CASH */}
        <ExpansionPanel
          title="Resumen Efectivo"
          amount={`$${cashTotal.toFixed(2)}`}
          amountClassName={valueClassName(cashTotal)}
        >
          <table className="w-full text-sm">
            <tbody>
              <tr className="border-b border-border last:border-0">
                <td className="p-1">
                  <span className="font-bold text-text">Ventas</span>
                </td>
                <td className="p-1 text-right">
                  <span className="font-bold text-success">${salesCashTotal.toFixed(2)}</span>
                </td>
              </tr>
              {hasCreditsModule && (
                <tr className="border-b border-border last:border-0">
                  <td className="p-1">
                    <span className="font-bold text-text">Créditos Pagados</span>
                  </td>
                  <td className="p-1 text-right">
                    <span className="font-bold text-success">${paidCreditsCashTotal.toFixed(2)}</span>
                  </td>
                </tr>
              )}
              {hasExpensesModule && (
                <tr className="border-b border-border last:border-0">
                  <td className="p-1">
                    <span className="font-bold text-text">Gastos</span>
                  </td>
                  <td className="p-1 text-right">
                    <span className="font-bold text-danger">${expensesCashTotal.toFixed(2)}</span>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </ExpansionPanel>
        {/* END CASH */}

        {/* BEGIN EXPENSES */}
        {hasExpensesModule && (
          <ExpansionPanel
            title={`Gastos (${expensesCount})`}
            amount={`$${expensesTotal.toFixed(2)}`}
            amountClassName="text-danger"
          >
            {expenses.length === 0 ? (
              <p className="py-4 text-center text-sm text-text-muted">
                {/* TODAY_STATS.NO_EXPENSE_FOUND */}
                {intl.formatMessage({ id: 'TODAY_STATS.NO_EXPENSE_FOUND' })}
              </p>
            ) : (
              <table className="w-full text-sm">
                <tbody>
                  {expenses.map((expense) => (
                    <tr key={expense.id} className="border-b border-border last:border-0">
                      <td className="p-1 text-text">
                        {intl.formatMessage({ id: EXPENSE_TYPE_KEYS[expense.type] })}
                      </td>
                      <td className="p-1 text-right text-danger">${expense.total.toFixed(2)}</td>
                      <td className="p-1 text-right">
                        <span className="rounded-full bg-success/10 px-2 py-0.5 text-xs font-semibold text-success">
                          {intl.formatMessage({ id: PAYMENT_TYPE_KEYS[expense.paymentType] })}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </ExpansionPanel>
        )}
        {/* END EXPENSES */}

        {/* BEGIN CREDITS */}
        {hasCreditsModule && (
          <ExpansionPanel
            title={`Créditos Por Cobrar (${creditsCount})`}
            amount={`$${creditsTotal.toFixed(2)}`}
            amountClassName="text-danger"
          >
            <SaleCreditsTable saleCredits={saleCredits} />
          </ExpansionPanel>
        )}
        {/* END CREDITS */}

        {/* BEGIN PAID CREDITS — Angular's literal template shows getPaidSaleCreditsTotal()
            (a currency sum) inside the "(...)" header slot, not a count. Preserved
            verbatim, not a bug fix. */}
        {hasCreditsModule && (
          <ExpansionPanel
            title={`Créditos Pagados (${paidSaleCreditsTotal})`}
            amount={`$${paidSaleCreditsTotal.toFixed(2)}`}
            amountClassName="text-success"
          >
            <SaleCreditsTable saleCredits={paidSaleCredits} />
          </ExpansionPanel>
        )}
        {/* END PAID CREDITS */}

        {/* BEGIN SALES */}
        <ExpansionPanel
          title={`Ventas (${ordersItemsCount} productos)`}
          amount={`$${ordersTotal.toFixed(2)}`}
          amountClassName="text-success"
        >
          {categories.map((category) => (
            <CategoryStats key={category.id} category={category} />
          ))}
        </ExpansionPanel>
        {/* END SALES */}
      </div>
    </Card>
  );
}

/**
 * Read-only rendering of `<app-sale-credit-list [saleCredits$]="...">` with no
 * `[readOnly]` binding (defaults `true` — no actions column), matching Angular's
 * `sale-credit-list.component.html` bare-table layout.
 */
function SaleCreditsTable({ saleCredits }: { saleCredits: SaleCredit[] }) {
  function formatDateOnly(date: Date): string {
    const d = new Date(date);
    const day = String(d.getUTCDate()).padStart(2, '0');
    const month = String(d.getUTCMonth() + 1).padStart(2, '0');
    const year = d.getUTCFullYear();
    return `${day}/${month}/${year}`;
  }

  return (
    <table className="w-full text-sm">
      <tbody>
        {saleCredits.map((saleCredit) => (
          <tr key={saleCredit.id} className="border-b border-border last:border-0">
            <td className="p-1">
              <span className="text-text">{saleCredit.client}</span>
            </td>
            <td className="p-1 text-right">
              <span className={saleCredit.isPaid ? 'text-success' : 'text-danger'}>
                ${saleCredit.total.toFixed(2)}
              </span>
            </td>
            <td className="p-1 text-right">
              {saleCredit.isPaid && (
                <span className="rounded-full bg-success/10 px-2 py-0.5 text-xs font-semibold text-success">
                  {formatDateOnly(saleCredit.paidDate)}
                </span>
              )}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default TodayStatsPage;
