// frontend/src/app/presentation/statistics/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import {
  ApexAxisChartSeries,
  ApexChart,
  ApexXAxis,
  ApexDataLabels,
  ApexStroke,
  ApexTitleSubtitle,
  ApexTooltip,
  ApexYAxis,
  NgApexchartsModule
} from 'ng-apexcharts';
import { SharedModule } from '../../shared/shared.module';
import { TranslationModule } from 'src/app/_modules/i18n/translation.module';
import { CurrencyData, CurrencyService } from 'src/app/application/entries/currency.service';
import { InventoryOfflineService } from 'src/app/application/entries/inventory-offline.service';
import { OrderOfflineService } from 'src/app/application/orders/order-offline.service';
import { LastMonthSaleProfitsComponent } from './last-month-sale-profits/last-month-sale-profits.component';
import { LastMonthSalesComponent } from './last-month-sales/last-month-sales.component';
import { BehaviorSubject } from 'rxjs';
import { TopProduct } from '../../_models/top-product.model';
import { ExpenseOfflineService } from 'src/app/application/expenses/expense-offline.service';
import { UserModel } from 'src/app/_services/auth/_models/auth-user.model';
import { AuthService } from 'src/app/_services/services.index';
import { AuthorizationService } from 'src/app/_services/authorization/authorization.service';
import { SaleCreditOfflineService } from 'src/app/application/credits/sale-credit-offline.service';

export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  xaxis: ApexXAxis;
  dataLabels?: ApexDataLabels;
  stroke?: ApexStroke;
  title?: ApexTitleSubtitle;
  tooltip?: ApexTooltip;
  yaxis?: ApexYAxis;
};

@Component({
    selector: 'app-dashboard',
    imports: [SharedModule, TranslationModule, NgApexchartsModule, LastMonthSaleProfitsComponent, LastMonthSalesComponent],
    templateUrl: './dashboard.component.html',
    styleUrl: './dashboard.component.scss'
})
export class DashboardComponent {
  currency: 'CUP' | 'USD';
  rate: number;

  currentUser: UserModel;
  hasExpensesModuleAvailable: boolean;
  hasCreditsModuleAvailable: boolean;

  salePriceToday: number = 0;
  salePriceYesterday: number = 0;

  saleProfitToday: number = 0;
  saleProfitYesterday: number = 0;

  expenseToday: number = 0;
  expenseYesterday: number = 0;

  margenBrutoMesActual: number = 0;
  margenBrutoMesAnterior: number = 0;

  inventoryCostTotal: number = 0;
  inventoryCostTotalYesterday: number = 0;

  unpaidSaleCreditsToday: number = 0;
  unpaidSaleCreditsYesterday: number = 0;

  topProfitProducts$: BehaviorSubject<TopProduct[]> = new BehaviorSubject<TopProduct[]>([]);
  topSaleQuantityProducts$: BehaviorSubject<TopProduct[]> = new BehaviorSubject<TopProduct[]>([]);

  valores = {
    ventasHoy: 2450,
    inventarioValorizado: 15300,
    ganancias: [120, 135, 150, 165], // 7, 30, 90, 365 días
    ventasSemana: [350, 400, 560, 480, 600, 700, 360]
  };

  ventasChartOptions: ChartOptions;
  gananciasChartOptions: ChartOptions;

  constructor(private currencyService: CurrencyService, private inventoryService: InventoryOfflineService, private orderService: OrderOfflineService, private expenseService: ExpenseOfflineService,
    private authService: AuthService,
    private authorizationService: AuthorizationService,
    private saleCreditService: SaleCreditOfflineService
  ) {
    this.currentUser = this.authService.currentUserValue;
    this.hasExpensesModuleAvailable = this.authorizationService.hasExpensesModuleAvailable();
    this.hasCreditsModuleAvailable = this.authorizationService.hasCreditsModuleAvailable();

    this.ventasChartOptions = this.getVentasChartOptions();
    this.gananciasChartOptions = this.getGananciasChartOptions();
    const currencyData: CurrencyData = this.currencyService.getCurrentCurrency();
    this.rate = currencyData.rate;
    this.currency = currencyData.currency;
    this.inventoryCostTotal = this.inventoryService.getInventoryCostTotal();
    this.inventoryCostTotalYesterday = this.inventoryService.getInventoryCostTotalYesterday();
    this.salePriceToday = this.orderService.getActiveOrdersPriceToday();
    this.salePriceYesterday = this.orderService.getActiveOrdersPriceYesterday();
    this.expenseToday = this.expenseService.getActiveExpensesPriceToday();
    this.expenseYesterday = this.expenseService.getActiveExpensesPriceYesterday();
    this.unpaidSaleCreditsToday = this.saleCreditService.getActiveUnpaidSaleCreditsPriceToday();
    this.unpaidSaleCreditsYesterday = this.saleCreditService.getActiveUnpaidSaleCreditsPriceYesterday();

    this.saleProfitToday = this.orderService.getActiveOrdersProfitToday();
    this.saleProfitYesterday = this.orderService.getActiveOrdersProfitYesterday();
    if (this.hasExpensesModuleAvailable) {
      this.saleProfitToday -= this.expenseToday;
      this.saleProfitYesterday -= this.expenseYesterday
    }

    this.topProfitProducts$.next(this.orderService.getTopProductsProfitInLastMonth());
    this.topSaleQuantityProducts$.next(this.orderService.getTopProductsSaleQuantityInLastMonth());

  }

  get divisor() {
    return this.currency === 'USD' ? this.rate : 1;
  }

  get sufijo() {
    return this.currency;
  }

  cambiarMoneda() {
    this.saveCurrency();
    this.updateCharts();
  }

  saveCurrency() {
    this.currencyService.setCurrency({ rate: this.rate, currency: this.currency });
  }

  updateCharts() {
    this.ventasChartOptions = this.getVentasChartOptions();
    this.gananciasChartOptions = this.getGananciasChartOptions();
  }

  getVentasChartOptions(): ChartOptions {
    return {
      series: [{
        name: `Ventas (${this.sufijo})`,
        data: this.valores.ventasSemana.map(v => +(v / this.divisor).toFixed(2))
      }],
      chart: { type: 'line', height: 300 },
      title: { text: 'Ventas Últimos 7 Días' },
      xaxis: { categories: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'] },
      stroke: { curve: 'smooth' }
    };
  }

  getGananciasChartOptions(): ChartOptions {
    return {
      series: [{
        name: `Ganancia promedio (${this.sufijo})`,
        data: this.valores.ganancias.map(g => +(g / this.divisor).toFixed(2))
      }],
      chart: { type: 'bar', height: 300 },
      title: { text: 'Ganancias Promedio (últimos días)' },
      xaxis: { categories: ['7 días', '30 días', '90 días', '365 días'] }
    };
  }

  get salesToday() {
    return (this.salePriceToday / this.divisor).toFixed(2);
  }

  get profitsToday() {
    return (this.saleProfitToday / this.divisor).toFixed(2);
  }

  get expensesToday() {
    return (this.expenseToday / this.divisor).toFixed(2);
  }

  get inventarioTotal() {
    return (this.inventoryCostTotal / this.divisor).toFixed(2);
  }

  get unpaidSaleCreditsTotal() {
    return (this.unpaidSaleCreditsToday / this.divisor).toFixed(2);
  }

  getTrendClass(actual: number, anterior: number): string {
    if (actual === anterior)
      return 'text-secondary';
    return actual >= anterior ? 'text-success' : 'text-danger';
  }

  getTrendIcon(actual: number, anterior: number): string {
    if (actual === anterior)
      return 'bi bi-dash-lg';
    return actual >= anterior ? 'bi bi-caret-up-fill' : 'bi bi-caret-down-fill';
  }

  getInventoryCostIcon() {
    return this.getTrendIcon(this.inventoryCostTotal, this.inventoryCostTotalYesterday);
  }

  getInventoryCostClass() {
    return this.getTrendClass(this.inventoryCostTotal, this.inventoryCostTotalYesterday);
  }

  getSaleCreditsIcon() {
    return this.getTrendIcon(this.unpaidSaleCreditsToday, this.unpaidSaleCreditsYesterday);
  }

  getSaleCreditsClass() {
    return this.getTrendClass(this.unpaidSaleCreditsToday, this.unpaidSaleCreditsYesterday);
  }

  getSalePriceIcon() {
    return this.getTrendIcon(this.salePriceToday, this.salePriceYesterday);
  }

  getSalePriceClass() {
    return this.getTrendClass(this.salePriceToday, this.salePriceYesterday);
  }

  getExpenseIcon() {
    return this.getTrendIcon(this.expenseToday, this.expenseYesterday);
  }

  getExpenseClass() {
    return this.getTrendClass(this.expenseToday, this.expenseYesterday);
  }

  getSaleProfitIcon() {
    return this.getTrendIcon(this.saleProfitToday, this.saleProfitYesterday);
  }

  getSaleProfitClass() {
    return this.getTrendClass(this.saleProfitToday, this.saleProfitYesterday);
  }

  getMargenBrutoIcon() {
    return this.getTrendIcon(this.margenBrutoMesActual, this.margenBrutoMesAnterior);
  }

  getMargenBrutoClass() {
    return this.getTrendClass(this.margenBrutoMesActual, this.margenBrutoMesAnterior);
  }

  trendSalePrice() {
    return this.trendTexto(this.salePriceToday, this.salePriceYesterday, "vs ayer");
  }

  trendExpense() {
    return this.trendTexto(this.expenseToday, this.expenseYesterday, "vs ayer");
  }

  trendSaleProfit() {
    return this.trendTexto(this.saleProfitToday, this.saleProfitYesterday, "vs ayer");
  }

  trendMargenBruto() {
    return this.trendTexto(this.margenBrutoMesActual, this.margenBrutoMesAnterior, "vs mes pasado");
  }

  trendInventoryCost() {
    return this.trendTexto(this.inventoryCostTotal, this.inventoryCostTotalYesterday, "vs ayer");
  }

  trendUnpaidSaleCredits() {
    return this.trendTexto(this.unpaidSaleCreditsToday, this.unpaidSaleCreditsYesterday, "vs ayer");
  }

  trendTexto(actual: number, anterior: number, sufijo: string) {
    const diferencia = Math.abs(actual - anterior);
    return diferencia !== 0 ? `${(diferencia / this.divisor).toFixed(2)} ${sufijo}` : `0 ${sufijo}`;
  }

}

<div class="card card-custom gutter-b">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label" [translate]="'DASHBOARD.HEADER'"></h3>
        </div>
    </div>
    <div class="card-body p-2">
        <div class="container py-4">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div class="d-flex align-items-center gap-2">
                    <label class="form-label mb-0">Moneda:</label>
                    <select class="form-select form-select-sm w-auto" [(ngModel)]="currency" (change)="cambiarMoneda()">
                        <option value="CUP">CUP</option>
                        <option value="USD">USD</option>
                    </select>
                    <input *ngIf="currency === 'USD'" type="number" class="form-control form-control-sm"
                        [(ngModel)]="rate" placeholder="1 USD = ? CUP" (input)="cambiarMoneda()" />
                </div>
            </div>


            <div class="row">
                <!-- Ventas Hoy -->
                <div class="col">
                    <div class="card bg-light text-dark position-relative">
                        <div class="card-body">
                            <!-- <i class="bi bi-cart-fill position-absolute top-0 end-0 m-3 fs-3 text-success"></i> -->
                            <h5 class="card-title" style="font-weight: 500;">Ventas Hoy</h5>
                            <p class="card-text fs-4 fw-bold" style="margin-bottom: 8px;">{{ salesToday }}</p>
                            <small [ngClass]="getSalePriceClass()" class="fw-bold fs-7">
                                <i [class]="getSalePriceIcon()"></i> {{ trendSalePrice() }}
                            </small>
                        </div>
                    </div>
                </div>

                <!-- Gastos Hoy -->
                <div *ngIf="hasExpensesModuleAvailable" class="col">
                    <div class="card bg-light text-dark position-relative">
                        <div class="card-body">
                            <!-- <i class="bi bi-cart-fill position-absolute top-0 end-0 m-3 fs-3 text-success"></i> -->
                            <h5 class="card-title" style="font-weight: 500;">Gastos Hoy</h5>
                            <p class="card-text fs-4 fw-bold" style="margin-bottom: 8px;">{{ expensesToday }}</p>
                            <small [ngClass]="getExpenseClass()" class="fw-bold fs-7">
                                <i [class]="getExpenseIcon()"></i> {{ trendExpense() }}
                            </small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Créditos Hoy -->
                <div *ngIf="hasCreditsModuleAvailable" class="col">
                    <div class="card bg-light text-dark position-relative">
                        <div class="card-body">
                            <h5 class="card-title" style="font-weight: 500;">Créditos Por Cobrar</h5>
                            <p class="card-text fs-4 fw-bold" style="margin-bottom: 8px;">{{ unpaidSaleCreditsTotal }}</p>
                            <small [ngClass]="getSaleCreditsClass()" class="fw-bold fs-7">
                                <i [class]="getSaleCreditsIcon()"></i>  {{ trendUnpaidSaleCredits() }}
                            </small>
                        </div>
                    </div>
                </div>

                <!-- Ganancias Hoy -->
                <div class="col">
                    <div class="card bg-light text-dark position-relative">
                        <div class="card-body">
                            <!-- <i class="bi bi-graph-up-arrow position-absolute top-0 end-0 m-3 fs-3 text-warning"></i> -->
                            <h5 class="card-title" style="font-weight: 500;">Ganancias Hoy</h5>
                            <p class="card-text fs-4 fw-bold" style="margin-bottom: 8px;">{{ profitsToday }}</p>
                            <small [ngClass]="getSaleProfitClass()" class="fw-bold fs-7">
                                <i [class]="getSaleProfitIcon()"></i> {{ trendSaleProfit() }}
                            </small>
                        </div>
                    </div>
                </div>

                <!-- Margen Bruto -->
                <!-- <div class="col">
                    <div class="card bg-light text-dark position-relative">
                        <div class="card-body">
                            <h5 class="card-title" style="font-weight: 500;">Margen Promedio</h5>
                            <p class="card-text fs-4 fw-bold" style="margin-bottom: 8px;">12.5%</p>
                            <small [ngClass]="getMargenBrutoClass()" class="fw-bold fs-7">
                                <i [class]="getMargenBrutoIcon()"></i> {{ trendMargenBruto() }}
                            </small>
                        </div>
                    </div>
                </div> -->

                <!-- Inventario Valorizado -->
                <!-- <div class="col">
                    <div class="card bg-light text-dark position-relative">
                        <div class="card-body">
                            <h5 class="card-title" style="font-weight: 500;">Valor Inventario</h5>
                            <p class="card-text fs-4 fw-bold" style="margin-bottom: 8px;">{{ inventarioTotal }}</p>
                            <small [ngClass]="getInventoryCostClass()" class="fw-bold fs-7">
                                <i [class]="getInventoryCostIcon()"></i>  {{ trendInventoryCost() }}
                            </small>
                        </div>
                    </div>
                </div> -->

            </div>

            <!-- <div class="card">
                <div class="row mt-3">
                    <div class="col">
                        <apx-chart [series]="gananciasChartOptions.series" [chart]="gananciasChartOptions.chart"
                            [xaxis]="gananciasChartOptions.xaxis" [title]="gananciasChartOptions.title">
                        </apx-chart>
                    </div>
                </div>
            </div> -->

            <app-last-month-sale-profits></app-last-month-sale-profits>
            <app-last-month-sales></app-last-month-sales>

            <div class="row mt-5">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Productos mayor ganancias (últimos 30 días)</h5>
                            <ul class="list-group">
                                <li *ngFor="let product of topProfitProducts$ | async" class="list-group-item d-flex justify-content-between">
                                    {{product.name}} 
                                    <span>{{(product.value / divisor).toFixed(2)}} {{sufijo}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- <div class="col-md-8">
                    <apx-chart [series]="ventasChartOptions.series" [chart]="ventasChartOptions.chart"
                        [xaxis]="ventasChartOptions.xaxis" [stroke]="ventasChartOptions.stroke"
                        [title]="ventasChartOptions.title">
                    </apx-chart>
                </div> -->
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Productos más vendidos (últimos 30 días)</h5>
                            <ul class="list-group">
                                <li *ngFor="let product of topSaleQuantityProducts$ | async" class="list-group-item d-flex justify-content-between">
                                    {{product.name}} 
                                    <span>{{product.value}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend-react/apps/web-store-pos/app/statistics/routes/dashboard.tsx
import { useState, useEffect } from 'react';
import { useIntl } from 'react-intl';
import { EFeatures } from '@store-mgmt/domain';
import { featureLoader } from '~/auth/routes/loaders';
import { useAuthStore } from '~/shared/lib/stores/auth-store';
import { hasExpensesModuleAvailable, hasCreditsModuleAvailable } from '~/shared/lib/auth/authorization-service';
import { OrderOfflineService } from '~/sales/lib/services/order-offline-service';
import type { ChartData, TopProduct } from '~/sales/lib/services/order-offline-service';
import { ExpenseOfflineService } from '~/expenses/lib/services/expense-offline-service';
import { SaleCreditOfflineService } from '~/sales/lib/services/sale-credit-offline-service';
import { getCurrentCurrency, setCurrency } from '~/statistics/lib/services/currency-service';
import { SalesChart } from '../components/sales-chart';
import { ProfitChart } from '../components/profit-chart';

export const clientLoader = featureLoader([EFeatures.Dashboard]);

/** 1:1 port of Angular's `getTrendClass` (dashboard.component.ts:193-196). */
export function getTrendClass(actual: number, anterior: number): string {
  if (actual === anterior) return 'text-secondary';
  return actual >= anterior ? 'text-success' : 'text-danger';
}

/**
 * Port of Angular's `getTrendIcon` (dashboard.component.ts:198-201). Angular renders a
 * `bi-caret-up-fill`/`bi-caret-down-fill`/`bi-dash-lg` Bootstrap-icon-font glyph; React has no
 * Bootstrap icon font, so the SAME three-way branch renders a plain Unicode glyph instead
 * (▲/▼/–) — same trend semantics, no new icon asset invented.
 */
export function getTrendGlyph(actual: number, anterior: number): string {
  if (actual === anterior) return '–';
  return actual >= anterior ? '▲' : '▼';
}

/** 1:1 port of Angular's `trendTexto` (dashboard.component.ts:275-278). */
function trendTexto(actual: number, anterior: number, divisor: number, sufijo: string): string {
  const diferencia = Math.abs(actual - anterior);
  return diferencia !== 0 ? `${(diferencia / divisor).toFixed(2)} ${sufijo}` : `0 ${sufijo}`;
}

function KpiCard({
  title,
  value,
  trendClass,
  trendGlyph,
  trendText,
}: {
  title: string;
  value: string;
  trendClass: string;
  trendGlyph: string;
  trendText: string;
}) {
  return (
    <div className="rounded border bg-white p-4 shadow-sm">
      <h5 className="text-sm font-medium text-gray-700">{title}</h5>
      <p className="mt-1 text-2xl font-bold text-gray-900">{value}</p>
      <small className={`text-xs font-bold ${trendClass}`}>
        <span aria-hidden="true">{trendGlyph}</span> {trendText}
      </small>
    </div>
  );
}

export function DashboardPage() {
  const intl = useIntl();
  const user = useAuthStore((s) => s.user);
  const storeId = user?.selectedStoreId ?? '';
  const hasExpensesModule = user ? hasExpensesModuleAvailable(user) : false;
  const hasCreditsModule = user ? hasCreditsModuleAvailable(user) : false;

  const [salesData, setSalesData] = useState<ChartData[]>([]);
  const [profitData, setProfitData] = useState<ChartData[]>([]);
  const [topProfitProducts, setTopProfitProducts] = useState<TopProduct[]>([]);
  const [topSaleQuantityProducts, setTopSaleQuantityProducts] = useState<TopProduct[]>([]);

  const [salePriceToday, setSalePriceToday] = useState(0);
  const [salePriceYesterday, setSalePriceYesterday] = useState(0);
  const [saleProfitToday, setSaleProfitToday] = useState(0);
  const [saleProfitYesterday, setSaleProfitYesterday] = useState(0);
  const [expenseToday, setExpenseToday] = useState(0);
  const [expenseYesterday, setExpenseYesterday] = useState(0);
  const [unpaidSaleCreditsToday, setUnpaidSaleCreditsToday] = useState(0);
  const [unpaidSaleCreditsYesterday, setUnpaidSaleCreditsYesterday] = useState(0);

  const [currency, setCurrencyValue] = useState<'CUP' | 'USD'>(() => getCurrentCurrency().currency);
  const [rate, setRateValue] = useState<number>(() => getCurrentCurrency().rate);

  useEffect(() => {
    const orderService = new OrderOfflineService(storeId);
    setSalesData(orderService.getLastMonthSales());
    setProfitData(orderService.getLastMonthSaleProfits());
    setTopProfitProducts(orderService.getTopProductsProfitInLastMonth());
    setTopSaleQuantityProducts(orderService.getTopProductsSaleQuantityInLastMonth());

    setSalePriceToday(orderService.getActiveOrdersPriceToday());
    setSalePriceYesterday(orderService.getActiveOrdersPriceYesterday());

    let profitToday = orderService.getActiveOrdersProfitToday();
    let profitYesterday = orderService.getActiveOrdersProfitYesterday();

    if (hasExpensesModule) {
      const expenseService = new ExpenseOfflineService(storeId);
      const todayExpense = expenseService.getActiveExpensesPriceToday();
      const yesterdayExpense = expenseService.getActiveExpensesPriceYesterday();
      setExpenseToday(todayExpense);
      setExpenseYesterday(yesterdayExpense);
      profitToday -= todayExpense;
      profitYesterday -= yesterdayExpense;
    } else {
      setExpenseToday(0);
      setExpenseYesterday(0);
    }

    setSaleProfitToday(profitToday);
    setSaleProfitYesterday(profitYesterday);

    if (hasCreditsModule) {
      const creditService = new SaleCreditOfflineService(storeId);
      setUnpaidSaleCreditsToday(creditService.getActiveUnpaidSaleCreditsPriceToday());
      setUnpaidSaleCreditsYesterday(creditService.getActiveUnpaidSaleCreditsPriceYesterday());
    } else {
      setUnpaidSaleCreditsToday(0);
      setUnpaidSaleCreditsYesterday(0);
    }
  }, [storeId, hasExpensesModule, hasCreditsModule]);

  const divisor = currency === 'USD' ? rate : 1;
  const sufijo = currency;

  function handleCurrencyChange(next: 'CUP' | 'USD') {
    setCurrencyValue(next);
    setCurrency({ currency: next, rate });
  }

  function handleRateChange(next: number) {
    setRateValue(next);
    setCurrency({ currency, rate: next });
  }

  const loadingMsg = intl.formatMessage({ id: 'GENERAL.LOADING' });
  const emptyMsg = intl.formatMessage({ id: 'STATISTICS.EMPTY_STATE' });

  return (
    <div className="space-y-6 p-4">
      {/* Header — Angular parity: dashboard.component.html:1-6 (card-header with the
          DASHBOARD.HEADER title and a bottom divider). */}
      <div className="border-b border-gray-200 pb-3">
        <h1 className="text-2xl font-semibold">
          {intl.formatMessage({ id: 'DASHBOARD.HEADER' })}
        </h1>
      </div>

      {/* Currency selector — Angular dashboard.component.html:9-20 (literal, untranslated
          "Moneda:" label, matching Angular's hardcoded template text). */}
      <div className="flex items-center gap-2">
        <label htmlFor="dashboard-currency" className="text-sm font-medium text-gray-700">
          Moneda:
        </label>
        <select
          id="dashboard-currency"
          value={currency}
          onChange={(e) => handleCurrencyChange(e.target.value as 'CUP' | 'USD')}
          className="rounded border border-gray-300 px-2 py-1 text-sm"
        >
          <option value="CUP">CUP</option>
          <option value="USD">USD</option>
        </select>
        {currency === 'USD' && (
          <input
            type="number"
            value={rate}
            onChange={(e) => handleRateChange(Number(e.target.value))}
            placeholder="1 USD = ? CUP"
            className="w-32 rounded border border-gray-300 px-2 py-1 text-sm"
          />
        )}
      </div>

      {/* KPI cards — Angular dashboard.component.html:24-84 (literal, untranslated titles).
          Angular lays them out as two `.row`s of two `.col`s each → two cards per row. */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <KpiCard
          title="Ventas Hoy"
          value={(salePriceToday / divisor).toFixed(2)}
          trendClass={getTrendClass(salePriceToday, salePriceYesterday)}
          trendGlyph={getTrendGlyph(salePriceToday, salePriceYesterday)}
          trendText={trendTexto(salePriceToday, salePriceYesterday, divisor, 'vs ayer')}
        />
        {hasExpensesModule && (
          <KpiCard
            title="Gastos Hoy"
            value={(expenseToday / divisor).toFixed(2)}
            trendClass={getTrendClass(expenseToday, expenseYesterday)}
            trendGlyph={getTrendGlyph(expenseToday, expenseYesterday)}
            trendText={trendTexto(expenseToday, expenseYesterday, divisor, 'vs ayer')}
          />
        )}
        {hasCreditsModule && (
          <KpiCard
            title="Créditos Por Cobrar"
            value={(unpaidSaleCreditsToday / divisor).toFixed(2)}
            trendClass={getTrendClass(unpaidSaleCreditsToday, unpaidSaleCreditsYesterday)}
            trendGlyph={getTrendGlyph(unpaidSaleCreditsToday, unpaidSaleCreditsYesterday)}
            trendText={trendTexto(unpaidSaleCreditsToday, unpaidSaleCreditsYesterday, divisor, 'vs ayer')}
          />
        )}
        <KpiCard
          title="Ganancias Hoy"
          value={(saleProfitToday / divisor).toFixed(2)}
          trendClass={getTrendClass(saleProfitToday, saleProfitYesterday)}
          trendGlyph={getTrendGlyph(saleProfitToday, saleProfitYesterday)}
          trendText={trendTexto(saleProfitToday, saleProfitYesterday, divisor, 'vs ayer')}
        />
      </div>

      {/* Sales Chart */}
      <section className="rounded border bg-white p-4 shadow-sm">
        <h2 className="mb-4 text-base font-semibold text-gray-700">
          {intl.formatMessage({ id: 'STATISTICS.SALES.TITLE' })}
        </h2>
        <SalesChart
          data={salesData}
          loadingMessage={loadingMsg}
          emptyMessage={emptyMsg}
        />
      </section>

      {/* Profit Chart */}
      <section className="rounded border bg-white p-4 shadow-sm">
        <h2 className="mb-4 text-base font-semibold text-gray-700">
          {intl.formatMessage({ id: 'STATISTICS.PROFIT.TITLE' })}
        </h2>
        <ProfitChart
          data={profitData}
          loadingMessage={loadingMsg}
          emptyMessage={emptyMsg}
        />
      </section>

      {/* Top-products lists — Angular dashboard.component.html:127-163 (literal, untranslated
          titles). */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="rounded border bg-white p-4 shadow-sm">
          <h5 className="mb-2 text-base font-semibold text-gray-700">
            Productos mayor ganancias (últimos 30 días)
          </h5>
          <ul className="divide-y divide-gray-100">
            {topProfitProducts.map((product) => (
              <li key={product.id} className="flex justify-between py-1 text-sm">
                <span>{product.name}</span>
                <span>
                  {(product.value / divisor).toFixed(2)} {sufijo}
                </span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded border bg-white p-4 shadow-sm">
          <h5 className="mb-2 text-base font-semibold text-gray-700">
            Productos más vendidos (últimos 30 días)
          </h5>
          <ul className="divide-y divide-gray-100">
            {topSaleQuantityProducts.map((product) => (
              <li key={product.id} className="flex justify-between py-1 text-sm">
                <span>{product.name}</span>
                <span>{product.value}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

export default DashboardPage;
