// frontend/src/app/presentation/sale/today-orders/order-item-list/order-item-list.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { TranslateService } from '@ngx-translate/core';
import { TranslationModule } from 'src/app/_modules/i18n/translation.module';
import { ShoppingCartService } from 'src/app/_services/order/shopping-cart.service';
import { OrderOfflineService } from 'src/app/application/orders/order-offline.service';
import { Result } from 'src/app/domain/commons/result';
import { OrderItem } from 'src/app/domain/entities/orders/order-item.model';
import { Order, OrderType } from 'src/app/domain/entities/orders/order.model';
import { SharedModule } from 'src/app/presentation/shared/shared.module';
import Swal from 'sweetalert2';
import { EditOrderModalComponent } from '../../edit-order-modal/edit-order-modal.component';

@Component({
    selector: 'app-order-item-list',
    imports: [SharedModule, TranslationModule],
    templateUrl: './order-item-list.component.html',
    styleUrl: './order-item-list.component.scss'
})
export class OrderItemListComponent implements OnInit {

  @Input() order: Order;
  @Input() readOnly: boolean = true;
  
  @Output() orderDeletedEmitter = new EventEmitter();
  @Output() orderItemUpdatedEmitter = new EventEmitter();
  @Output() orderItemDeletedEmitter = new EventEmitter();

  constructor(private shoppingCartService: ShoppingCartService, private translate: TranslateService, private orderService: OrderOfflineService, private modalService: NgbModal) { }

  ngOnInit(): void {
  }

  deactivateOrder(order: Order) {
    Swal.fire({
      title: this.translate.instant('GENERAL.DELETE_CONFIRM_TITLE'),
      text: this.translate.instant('GENERAL.DELETE_CONFIRM_MESSAGE_A',
        { name: this.translate.instant('TODAY_ORDERS.TEXT') }),
      icon: "question",
      showCancelButton: true,
      confirmButtonColor: "#3456ff",
      cancelButtonColor: "#dc3545",
      confirmButtonText: this.translate.instant('GENERAL.YES'),
      cancelButtonText: this.translate.instant('GENERAL.NO'),
    }).then((result) => {
      if (result.isConfirmed) {
        const result: Result = this.orderService.deactivateOrder(order.id);
        if (result.succeeded)
          this.orderDeletedEmitter.emit();
        else
          this.showErrorMessage(["La venta no pudo ser cancelada. Inténtelo más tarde y si persiste el problema contacte al soporte técnico."]);
      }
    });
  }

  openEditOrderModal(order: Order) {
    const modalRef = this.modalService.open(EditOrderModalComponent, { centered: true, size: "lg" });
    modalRef.componentInstance.order = order;
    modalRef.componentInstance.orderUpdatedEmitter.subscribe((updatedOrder: Order) => {
      order.paymentType = updatedOrder.paymentType;
    });
  }

  activateOrder(order: Order) {
    this.orderService.activateOrder(order.id);
  }

  sendOrderToShoppingCart() {
    if (this.shoppingCartService.getCartItems().length > 0) {
      Swal.fire({
        title: this.translate.instant('TODAY_ORDERS.DISAPPROVE_CONFIRM_TITLE'),
        text: this.translate.instant('TODAY_ORDERS.SEND_TO_CART_CONFIRM_MESSAGE'),
        icon: "question",
        showCancelButton: true,
        confirmButtonColor: "#3456ff",
        cancelButtonColor: "#dc3545",
        confirmButtonText: this.translate.instant('GENERAL.YES'),
        cancelButtonText: this.translate.instant('GENERAL.NO'),
      }).then((result) => {
        if (result.isConfirmed) {
          this.shoppingCartService.clearCart();
          this.addOrderItemsToShoppingCart();
        }
      });
      return;
    }
    this.addOrderItemsToShoppingCart();
  }

  addOrderItemsToShoppingCart() {
    this.order.orderItems.forEach(item => {
      this.shoppingCartService.addCartItem(OrderType.Normal, item.productId, item.quantity, item.price);
    });
  }

  onDeteleOrder() {
    Swal.fire({
      title: this.translate.instant('GENERAL.DELETE_CONFIRM_TITLE'),
      text: this.translate.instant('GENERAL.DELETE_CONFIRM_MESSAGE',
        { name: this.translate.instant('TODAY_ORDER.TEXT') }),
      icon: "question",
      showCancelButton: true,
      confirmButtonColor: "#3456ff",
      cancelButtonColor: "#dc3545",
      confirmButtonText: this.translate.instant('GENERAL.YES'),
      cancelButtonText: this.translate.instant('GENERAL.NO'),
    }).then((result) => {
      if (result.isConfirmed) {
        this.orderService.delete(this.order.id).subscribe(response => {
          if (response.succeeded) {
            this.orderDeletedEmitter.emit();
          }
          else {
            console.log("Error deleting order with id: " + this.order.id);
            this.showErrorMessage(response.errors);
          }
        }, error => {
          console.error("Error creating order: ", error);
        });
      }
    });
  }

  showErrorMessage(errors: string[]) {
    Swal.fire({
      title: this.translate.instant('GENERAL.ERROR'),
      text: this.translate.instant('TODAY_ORDERS.ERROR_DELETING_ORDER',
        { message: errors.join("<br>") }),
      icon: "error",
      showCancelButton: false,
      confirmButtonColor: "#3456ff",
      cancelButtonColor: "#dc3545",
      confirmButtonText: this.translate.instant('GENERAL.OK'),
    })
  }

  openEditOrderItemModal(orderItem: OrderItem) {

  }

  onDeteleOrderItem(orderItemId: string) {

  }

}

<div *ngIf="!readOnly" class="row text-end mb-2">
    <div class="col text-end">
        <button mat-fab extended color="primary" (click)="openEditOrderModal(order)">
            <mat-icon>edit</mat-icon>
            {{'GENERAL.EDIT'| translate}}
        </button>
        @if (order.isActive) {
        <button mat-fab extended color="primary" (click)="deactivateOrder(order)" style="margin-left: 10px;">
            <mat-icon color="warn">delete</mat-icon>
            {{'GENERAL.DELETE'| translate}}
        </button>
        } 
        <!-- @else {
        <button mat-fab extended color="primary" (click)="activateOrder(order)">
            <mat-icon>edit</mat-icon>
            {{'TODAY_ORDERS.ACTIVATE_ORDER'| translate}}
        </button>
        } -->
    </div>
</div>

<div class="table-responsive">
    <table class="table table-borderless table-vertical-center">
        <tbody>
            <tr *ngFor="let item of order.orderItems" class="border-1">
                <td class="p-2">
                    <span class="text-dark font-weight-bold mb-1 font-size-lg">
                        {{item.name}}
                    </span>
                </td>
                <td class="text-end p-2">
                    <span class="label label-success font-weight-bold font-size-lg">
                        {{item.quantity}}
                    </span>
                </td>
                <td class="text-end p-2">
                    <span class="font-weight-bold mb-1 font-size-lg">
                        {{(item.price * item.quantity) | currency:'USD':'symbol':'1.2-2'}}
                    </span>
                </td>
            </tr>
        </tbody>
    </table>
</div>

// frontend-react/apps/web-store-pos/app/sales/components/order-item-list.tsx
import { useIntl } from 'react-intl';
import type { Order } from '@store-mgmt/domain';
import { Button } from '~/shared/components/ui/button';
import { confirmDialog, showAcknowledgeError } from '~/shared/lib/blocking-alert';
import { formatCurrency } from '~/shared/lib/format-currency';
import { round2 } from '~/shared/lib/money';

interface OrderItemListProps {
  order: Order;
  /** Angular default is `true` (read-only, no actions) — set `false` to show Editar/Eliminar. */
  readOnly?: boolean;
  onEditOrder?: (order: Order) => void;
  /** Returns `true` on success, `false` on failure — mirrors Angular's
   * `orderService.deactivateOrder(order.id)` returning a `Result` with `succeeded`. */
  onDeactivateOrder?: (order: Order) => boolean;
}

/**
 * Matches Angular's `order-item-list.component.html`: optional action row
 * (Editar / Eliminar, shown only when `readOnly` is false and only while the
 * order `isActive`), followed by the order's item table (name, quantity,
 * line total). No header row in Angular's markup — table body only.
 */
export function OrderItemList({
  order,
  readOnly = true,
  onEditOrder,
  onDeactivateOrder,
}: OrderItemListProps) {
  const intl = useIntl();

  // Angular: deactivateOrder (order-item-list.component.ts:34-53) — Swal.fire({ title:
  // GENERAL.DELETE_CONFIRM_TITLE, text: GENERAL.DELETE_CONFIRM_MESSAGE_A with
  // name=TODAY_ORDERS.TEXT, icon: 'question', showCancelButton: true,
  // confirmButtonColor: '#3456ff', cancelButtonColor: '#dc3545', confirmButtonText: YES,
  // cancelButtonText: NO }). On confirm, deactivate; on failure, showErrorMessage (a
  // Swal.fire OK-only error dialog with the hardcoded Angular literal below).
  async function handleDeactivateClick() {
    const confirmed = await confirmDialog({
      title: intl.formatMessage({ id: 'GENERAL.DELETE_CONFIRM_TITLE' }),
      message: intl.formatMessage(
        { id: 'GENERAL.DELETE_CONFIRM_MESSAGE_A' },
        { name: intl.formatMessage({ id: 'TODAY_ORDERS.TEXT' }) },
      ),
      confirmButtonText: intl.formatMessage({ id: 'GENERAL.YES' }),
      cancelButtonText: intl.formatMessage({ id: 'GENERAL.NO' }),
    });
    if (!confirmed) return;

    const succeeded = onDeactivateOrder?.(order) ?? true;
    if (!succeeded) {
      showAcknowledgeError({
        title: intl.formatMessage({ id: 'GENERAL.ERROR' }),
        message: intl.formatMessage(
          { id: 'TODAY_ORDERS.ERROR_DELETING_ORDER' },
          {
            // Angular's own hardcoded Spanish literal (order-item-list.component.ts:51),
            // not an i18n key — preserved verbatim, same precedent as the CSV importer fix.
            message:
              'La venta no pudo ser cancelada. Inténtelo más tarde y si persiste el problema contacte al soporte técnico.',
          },
        ),
        confirmButtonText: intl.formatMessage({ id: 'GENERAL.OK' }),
      });
    }
  }

  return (
    <div className="space-y-2">
      {!readOnly && (
        <div className="flex justify-end gap-2">
          <Button variant="fab" onClick={() => onEditOrder?.(order)} data-testid="edit-order-button">
            {/* GENERAL.EDIT */}
            {intl.formatMessage({ id: 'GENERAL.EDIT' })}
          </Button>
          {order.isActive && (
            <Button
              variant="danger"
              onClick={handleDeactivateClick}
              data-testid="deactivate-order-button"
            >
              {/* GENERAL.DELETE */}
              {intl.formatMessage({ id: 'GENERAL.DELETE' })}
            </Button>
          )}
        </div>
      )}

      {order.orderItems && (
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <tbody>
              {order.orderItems.map((item, idx) => (
                <tr key={idx}>
                  <td className="p-2">
                    <span className="font-semibold text-text">{item.name}</span>
                  </td>
                  <td className="p-2 text-right">
                    <span className="text-xs font-semibold text-primary">{item.quantity}</span>
                  </td>
                  <td className="p-2 text-right">
                    <span className="font-semibold text-text">
                      {formatCurrency(round2(item.price * item.quantity))}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
